name: DanteNguyen1008/android-UniversalMusicPlayer
author:
  name: null
  email: an.nguyenquocduy@gmail.com
  url: null
copyright: 2015 null
description: 'This sample shows how to implement an audio media app that works across multiple form factors and provide a consistent user experience on Android phones, tablets, Auto, Wear and Cast devices'
